<?php

use App\Models\Attendance;
use App\Models\Justification;
use App\Models\Subject;
use App\Models\User;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;

test('lists only the authenticated student justifications', function () {
    $group = makeActiveGroup();
    $student = User::factory()->student()->create(['governance_user_id' => 1, 'group_id' => $group->id]);
    $otherStudent = User::factory()->student()->create(['governance_user_id' => 2, 'group_id' => $group->id]);

    $mine = Justification::factory()->create([
        'attendance_id' => Attendance::factory()->absent()->create(['student_id' => $student->id]),
    ]);
    Justification::factory()->create([
        'attendance_id' => Attendance::factory()->absent()->create(['student_id' => $otherStudent->id]),
    ]);

    $token = fakeGovernanceAuth($student);

    $response = $this->getJson('/api/v1/alumno/justifications', ['Authorization' => "Bearer {$token}"]);

    $response->assertOk()
        ->assertJsonCount(1, 'data')
        ->assertJsonPath('data.0.id', $mine->id);
});

test('rejects viewing another student justification', function () {
    $group = makeActiveGroup();
    $student = User::factory()->student()->create(['governance_user_id' => 1, 'group_id' => $group->id]);
    $otherStudent = User::factory()->student()->create(['governance_user_id' => 2, 'group_id' => $group->id]);

    $justification = Justification::factory()->create([
        'attendance_id' => Attendance::factory()->absent()->create(['student_id' => $otherStudent->id]),
    ]);

    $token = fakeGovernanceAuth($student);

    $response = $this->getJson("/api/v1/alumno/justifications/{$justification->id}", ['Authorization' => "Bearer {$token}"]);

    $response->assertForbidden()->assertJsonPath('error_code', 'PERM01');
});

test('creates a justification for an absent attendance record', function () {
    Storage::fake('public');

    $group = makeActiveGroup();
    $subject = Subject::factory()->create();
    $schedule = makeActiveSchedule($group, $subject);

    $student = User::factory()->student()->create(['governance_user_id' => 1, 'group_id' => $group->id]);

    $attendance = Attendance::factory()->absent()->create([
        'student_id' => $student->id,
        'schedule_id' => $schedule->id,
    ]);

    $token = fakeGovernanceAuth($student);

    $response = $this->post(
        "/api/v1/alumno/subjects/{$subject->id}/attendance/{$attendance->id}/justify",
        [
            'reason' => 'Cita médica el día de la falta.',
            'evidence' => UploadedFile::fake()->create('evidencia.pdf', 100, 'application/pdf'),
        ],
        ['Authorization' => "Bearer {$token}"]
    );

    $response->assertCreated()
        ->assertJsonPath('data.status', 'PENDIENTE')
        ->assertJsonPath('data.subject.id', $subject->id);

    $this->assertDatabaseHas('justifications', [
        'attendance_id' => $attendance->id,
        'justified_by_user_id' => $student->id,
        'status' => 'PENDIENTE',
    ]);
});

test('creates a justification for a falta auto-generated by the class-session auto-close', function () {
    Storage::fake('public');

    $group = makeActiveGroup();
    $subject = Subject::factory()->create();
    $schedule = makeActiveSchedule($group, $subject);

    $student = User::factory()->student()->create(['governance_user_id' => 1, 'group_id' => $group->id]);

    // El cron class-sessions:auto-close (CloseClassSessionService) crea estas FALTA con
    // method=SISTEMA, a diferencia de una marcada a mano por el profesor (MANUAL). No debe
    // haber ninguna diferencia: cualquier FALTA sin justificante previo se puede justificar.
    $attendance = Attendance::factory()->absent()->create([
        'student_id' => $student->id,
        'schedule_id' => $schedule->id,
        'method' => 'SISTEMA',
    ]);

    $token = fakeGovernanceAuth($student);

    $response = $this->post(
        "/api/v1/alumno/subjects/{$subject->id}/attendance/{$attendance->id}/justify",
        [
            'reason' => 'La falta la genero el cierre automatico de la clase, pero si asisti.',
            'evidence' => UploadedFile::fake()->create('evidencia.pdf', 100, 'application/pdf'),
        ],
        ['Authorization' => "Bearer {$token}"]
    );

    $response->assertCreated()->assertJsonPath('data.status', 'PENDIENTE');

    $this->assertDatabaseHas('justifications', [
        'attendance_id' => $attendance->id,
        'justified_by_user_id' => $student->id,
        'status' => 'PENDIENTE',
    ]);
});

test('rejects justifying an attendance that is not absent', function () {
    Storage::fake('public');

    $group = makeActiveGroup();
    $subject = Subject::factory()->create();
    $schedule = makeActiveSchedule($group, $subject);

    $student = User::factory()->student()->create(['governance_user_id' => 1, 'group_id' => $group->id]);

    $attendance = Attendance::factory()->present()->create([
        'student_id' => $student->id,
        'schedule_id' => $schedule->id,
    ]);

    $token = fakeGovernanceAuth($student);

    $response = $this->post(
        "/api/v1/alumno/subjects/{$subject->id}/attendance/{$attendance->id}/justify",
        [
            'reason' => 'Intento justificar una asistencia presente.',
            'evidence' => UploadedFile::fake()->create('evidencia.pdf', 100, 'application/pdf'),
        ],
        ['Authorization' => "Bearer {$token}"]
    );

    $response->assertStatus(409)->assertJsonPath('error_code', 'ATT04');
});

test('rejects justifying an attendance that already has a justification', function () {
    Storage::fake('public');

    $group = makeActiveGroup();
    $subject = Subject::factory()->create();
    $schedule = makeActiveSchedule($group, $subject);

    $student = User::factory()->student()->create(['governance_user_id' => 1, 'group_id' => $group->id]);

    $attendance = Attendance::factory()->absent()->create([
        'student_id' => $student->id,
        'schedule_id' => $schedule->id,
    ]);

    Justification::factory()->create(['attendance_id' => $attendance->id]);

    $token = fakeGovernanceAuth($student);

    $response = $this->post(
        "/api/v1/alumno/subjects/{$subject->id}/attendance/{$attendance->id}/justify",
        [
            'reason' => 'Ya tiene un justificante este registro.',
            'evidence' => UploadedFile::fake()->create('evidencia.pdf', 100, 'application/pdf'),
        ],
        ['Authorization' => "Bearer {$token}"]
    );

    $response->assertStatus(409)->assertJsonPath('error_code', 'JUST03');
});

test('shows the real reviewer and comment once a tutor reviews the justification', function () {
    $group = makeActiveGroup();
    $student = User::factory()->student()->create(['governance_user_id' => 1, 'group_id' => $group->id]);
    $tutor = makeTutorForGroup($group, 2);

    $justification = Justification::factory()->create([
        'attendance_id' => Attendance::factory()->absent()->create(['student_id' => $student->id]),
    ]);

    // Tokens distintos: el cache de ResolveGovernanceUser guarda por token, y ambos
    // usuarios necesitan resolver a identidades distintas dentro del mismo test.
    $tutorToken = fakeGovernanceAuth($tutor, 'tutor-token');

    $this->patchJson(
        "/api/v1/tutor/students/{$student->id}/justifications/{$justification->id}",
        ['status' => 'ACEPTADO', 'comment' => 'Justificante válido.'],
        ['Authorization' => "Bearer {$tutorToken}"]
    )->assertOk();

    $studentToken = fakeGovernanceAuth($student, 'student-token');

    $response = $this->getJson("/api/v1/alumno/justifications/{$justification->id}", ['Authorization' => "Bearer {$studentToken}"]);

    $response->assertOk()
        ->assertJsonPath('data.status', 'ACEPTADO')
        ->assertJsonPath('data.reviewed_by.id', $tutor->id)
        ->assertJsonPath('data.comment', 'Justificante válido.');
});

test('updates a pending justification', function () {
    $group = makeActiveGroup();
    $student = User::factory()->student()->create(['governance_user_id' => 1, 'group_id' => $group->id]);

    $justification = Justification::factory()->create([
        'attendance_id' => Attendance::factory()->absent()->create(['student_id' => $student->id]),
        'reason' => 'Motivo original.',
    ]);

    $token = fakeGovernanceAuth($student);

    $response = $this->putJson("/api/v1/alumno/justifications/{$justification->id}", [
        'reason' => 'Motivo corregido con mas contexto.',
    ], ['Authorization' => "Bearer {$token}"]);

    $response->assertOk()->assertJsonPath('data.reason', 'Motivo corregido con mas contexto.');

    $this->assertDatabaseHas('justifications', [
        'id' => $justification->id,
        'reason' => 'Motivo corregido con mas contexto.',
    ]);
});

test('rejects updating another student justification', function () {
    $group = makeActiveGroup();
    $student = User::factory()->student()->create(['governance_user_id' => 1, 'group_id' => $group->id]);
    $otherStudent = User::factory()->student()->create(['governance_user_id' => 2, 'group_id' => $group->id]);

    $justification = Justification::factory()->create([
        'attendance_id' => Attendance::factory()->absent()->create(['student_id' => $otherStudent->id]),
    ]);

    $token = fakeGovernanceAuth($student);

    $response = $this->putJson("/api/v1/alumno/justifications/{$justification->id}", [
        'reason' => 'Intento de editar un justificante ajeno.',
    ], ['Authorization' => "Bearer {$token}"]);

    $response->assertForbidden()->assertJsonPath('error_code', 'PERM01');
});

test('rejects updating a justification that was already reviewed', function () {
    $group = makeActiveGroup();
    $student = User::factory()->student()->create(['governance_user_id' => 1, 'group_id' => $group->id]);

    $justification = Justification::factory()->accepted()->create([
        'attendance_id' => Attendance::factory()->absent()->create(['student_id' => $student->id]),
    ]);

    $token = fakeGovernanceAuth($student);

    $response = $this->putJson("/api/v1/alumno/justifications/{$justification->id}", [
        'reason' => 'Ya no deberia poder editar esto.',
    ], ['Authorization' => "Bearer {$token}"]);

    $response->assertConflict()->assertJsonPath('error_code', 'JUST02');
});

test('deletes a pending justification when confirmed', function () {
    $group = makeActiveGroup();
    $student = User::factory()->student()->create(['governance_user_id' => 1, 'group_id' => $group->id]);

    $justification = Justification::factory()->create([
        'attendance_id' => Attendance::factory()->absent()->create(['student_id' => $student->id]),
    ]);

    $token = fakeGovernanceAuth($student);

    $response = $this->deleteJson("/api/v1/alumno/justifications/{$justification->id}?confirm=true", [], ['Authorization' => "Bearer {$token}"]);

    $response->assertOk();
    $this->assertDatabaseMissing('justifications', ['id' => $justification->id]);
});

test('requires confirmation to delete a justification', function () {
    $group = makeActiveGroup();
    $student = User::factory()->student()->create(['governance_user_id' => 1, 'group_id' => $group->id]);

    $justification = Justification::factory()->create([
        'attendance_id' => Attendance::factory()->absent()->create(['student_id' => $student->id]),
    ]);

    $token = fakeGovernanceAuth($student);

    $response = $this->deleteJson("/api/v1/alumno/justifications/{$justification->id}", [], ['Authorization' => "Bearer {$token}"]);

    $response->assertStatus(422)->assertJsonPath('error_code', 'VAL03');
    $this->assertDatabaseHas('justifications', ['id' => $justification->id]);
});

test('rejects deleting another student justification', function () {
    $group = makeActiveGroup();
    $student = User::factory()->student()->create(['governance_user_id' => 1, 'group_id' => $group->id]);
    $otherStudent = User::factory()->student()->create(['governance_user_id' => 2, 'group_id' => $group->id]);

    $justification = Justification::factory()->create([
        'attendance_id' => Attendance::factory()->absent()->create(['student_id' => $otherStudent->id]),
    ]);

    $token = fakeGovernanceAuth($student);

    $response = $this->deleteJson("/api/v1/alumno/justifications/{$justification->id}?confirm=true", [], ['Authorization' => "Bearer {$token}"]);

    $response->assertForbidden()->assertJsonPath('error_code', 'PERM01');
    $this->assertDatabaseHas('justifications', ['id' => $justification->id]);
});

test('rejects deleting a justification that was already reviewed', function () {
    $group = makeActiveGroup();
    $student = User::factory()->student()->create(['governance_user_id' => 1, 'group_id' => $group->id]);

    $justification = Justification::factory()->rejected()->create([
        'attendance_id' => Attendance::factory()->absent()->create(['student_id' => $student->id]),
    ]);

    $token = fakeGovernanceAuth($student);

    $response = $this->deleteJson("/api/v1/alumno/justifications/{$justification->id}?confirm=true", [], ['Authorization' => "Bearer {$token}"]);

    $response->assertConflict()->assertJsonPath('error_code', 'JUST02');
    $this->assertDatabaseHas('justifications', ['id' => $justification->id]);
});

test('rejects justifying an attendance that does not exist', function () {
    Storage::fake('public');

    $group = makeActiveGroup();
    $subject = Subject::factory()->create();
    makeActiveSchedule($group, $subject);

    $student = User::factory()->student()->create(['governance_user_id' => 1, 'group_id' => $group->id]);
    $token = fakeGovernanceAuth($student);

    $response = $this->post(
        "/api/v1/alumno/subjects/{$subject->id}/attendance/999999/justify",
        [
            'reason' => 'Este registro de asistencia no existe.',
            'evidence' => UploadedFile::fake()->create('evidencia.pdf', 100, 'application/pdf'),
        ],
        ['Authorization' => "Bearer {$token}"]
    );

    $response->assertNotFound()->assertJsonPath('error_code', 'ATT03');
});
